import type { StockAvatar } from "@/lib/types/avatar";

/**
 * Stock AI-avatar catalog.
 *
 * MVP source: placeholder images keyed by id. Production swap-in is a
 * Cloudflare R2 bucket mirroring the same filenames — update `imageUrl` and
 * `thumbnailUrl` to point at the CDN without touching any consumer code.
 * The generator pipeline in `scripts/generate-avatars.ts` documents the
 * pipeline that fans out (vibe x demographic x gesture) prompt presets to
 * an image model and writes the resulting metadata + thumbnails into this
 * file.
 *
 * Tier gating:
 *   - `minTier: null` → available on free/trial
 *   - `"starter"` → any paid plan
 *   - `"creator"` / `"studio"` → premium-only (matches HeyGen twin gating)
 *
 * Vibe taxonomy (expanded to 8 vibes to match the builder/seller audience):
 *   Founder · Host · Teacher · Reporter · Creator · Expert · Builder · Seller
 */
export const STOCK_AVATARS: StockAvatar[] = [
  // ── Founder vibe ─────────────────────────────────────────────────────────
  {
    id: "stock-founder-01",
    name: "Nora",
    imageUrl: "https://i.pravatar.cc/600?img=1",
    thumbnailUrl: "https://i.pravatar.cc/150?img=1",
    gender: "female",
    vibe: "founder",
    description: "Calm founder voice. Warm, measured, builds trust fast.",
    minTier: null,
  },
  {
    id: "stock-founder-02",
    name: "Malik",
    imageUrl: "https://i.pravatar.cc/600?img=12",
    thumbnailUrl: "https://i.pravatar.cc/150?img=12",
    gender: "male",
    vibe: "founder",
    description: "Technical founder. Speaks precisely, earns credibility fast.",
    minTier: null,
  },
  {
    id: "stock-founder-03",
    name: "Elena",
    imageUrl: "https://i.pravatar.cc/600?img=49",
    thumbnailUrl: "https://i.pravatar.cc/150?img=49",
    gender: "female",
    vibe: "founder",
    description: "Executive presence. Reads like a keynote opener.",
    minTier: "studio",
  },
  {
    id: "stock-founder-04",
    name: "Yoon",
    imageUrl: "https://i.pravatar.cc/600?img=13",
    thumbnailUrl: "https://i.pravatar.cc/150?img=13",
    gender: "neutral",
    vibe: "founder",
    description: "Indie-hacker energy. Direct, scrappy, unapologetic.",
    minTier: "starter",
  },
  {
    id: "stock-founder-05",
    name: "Rin",
    imageUrl: "https://i.pravatar.cc/600?img=22",
    thumbnailUrl: "https://i.pravatar.cc/150?img=22",
    gender: "female",
    vibe: "founder",
    description: "Second-time founder calm. Confident without overselling.",
    minTier: "starter",
  },

  // ── Host vibe ────────────────────────────────────────────────────────────
  {
    id: "stock-host-01",
    name: "Priya",
    imageUrl: "https://i.pravatar.cc/600?img=5",
    thumbnailUrl: "https://i.pravatar.cc/150?img=5",
    gender: "female",
    vibe: "host",
    description: "High-energy host. Reads like a podcaster.",
    minTier: null,
  },
  {
    id: "stock-host-02",
    name: "Theo",
    imageUrl: "https://i.pravatar.cc/600?img=33",
    thumbnailUrl: "https://i.pravatar.cc/150?img=33",
    gender: "male",
    vibe: "host",
    description: "Conversational, playful. Keeps a thread for 60 seconds.",
    minTier: "starter",
  },
  {
    id: "stock-host-03",
    name: "Jules",
    imageUrl: "https://i.pravatar.cc/600?img=26",
    thumbnailUrl: "https://i.pravatar.cc/150?img=26",
    gender: "neutral",
    vibe: "host",
    description: "Late-night host energy. Quick wit, confident cadence.",
    minTier: "studio",
  },
  {
    id: "stock-host-04",
    name: "Beatrice",
    imageUrl: "https://i.pravatar.cc/600?img=48",
    thumbnailUrl: "https://i.pravatar.cc/150?img=48",
    gender: "female",
    vibe: "host",
    description: "Morning-show warmth. Great for welcoming hooks.",
    minTier: null,
  },

  // ── Teacher vibe ─────────────────────────────────────────────────────────
  {
    id: "stock-teacher-01",
    name: "Amelia",
    imageUrl: "https://i.pravatar.cc/600?img=9",
    thumbnailUrl: "https://i.pravatar.cc/150?img=9",
    gender: "female",
    vibe: "teacher",
    description: "Explains complex ideas patiently. Classroom cadence.",
    minTier: "starter",
  },
  {
    id: "stock-teacher-02",
    name: "Hiro",
    imageUrl: "https://i.pravatar.cc/600?img=51",
    thumbnailUrl: "https://i.pravatar.cc/150?img=51",
    gender: "male",
    vibe: "teacher",
    description: "Technical deep-dive. Calm, thorough, earns trust over time.",
    minTier: "starter",
  },
  {
    id: "stock-teacher-03",
    name: "Chloe",
    imageUrl: "https://i.pravatar.cc/600?img=11",
    thumbnailUrl: "https://i.pravatar.cc/150?img=11",
    gender: "female",
    vibe: "teacher",
    description: "Data-viz explainer. Walks through charts and numbers cleanly.",
    minTier: "solo",
  },
  {
    id: "stock-teacher-04",
    name: "Rashid",
    imageUrl: "https://i.pravatar.cc/600?img=59",
    thumbnailUrl: "https://i.pravatar.cc/150?img=59",
    gender: "male",
    vibe: "teacher",
    description: "Senior mentor voice. Grounded, encouraging, slow-paced.",
    minTier: "starter",
  },
  {
    id: "stock-teacher-05",
    name: "Inez",
    imageUrl: "https://i.pravatar.cc/600?img=44",
    thumbnailUrl: "https://i.pravatar.cc/150?img=44",
    gender: "female",
    vibe: "teacher",
    description: "Bootcamp instructor energy. High information density.",
    minTier: "solo",
  },

  // ── Reporter vibe ────────────────────────────────────────────────────────
  {
    id: "stock-reporter-01",
    name: "Zara",
    imageUrl: "https://i.pravatar.cc/600?img=20",
    thumbnailUrl: "https://i.pravatar.cc/150?img=20",
    gender: "female",
    vibe: "reporter",
    description: "News-style delivery. Short sentences, sharp hooks.",
    minTier: "solo",
  },
  {
    id: "stock-reporter-02",
    name: "Dmitri",
    imageUrl: "https://i.pravatar.cc/600?img=15",
    thumbnailUrl: "https://i.pravatar.cc/150?img=15",
    gender: "male",
    vibe: "reporter",
    description: "Industry-insider tone. Sounds like a trade publication.",
    minTier: "solo",
  },
  {
    id: "stock-reporter-03",
    name: "Tanvi",
    imageUrl: "https://i.pravatar.cc/600?img=43",
    thumbnailUrl: "https://i.pravatar.cc/150?img=43",
    gender: "female",
    vibe: "reporter",
    description: "Investigative-beat energy. Leans into surprising stats.",
    minTier: "creator",
  },
  {
    id: "stock-reporter-04",
    name: "Felix",
    imageUrl: "https://i.pravatar.cc/600?img=65",
    thumbnailUrl: "https://i.pravatar.cc/150?img=65",
    gender: "male",
    vibe: "reporter",
    description: "Business-channel anchor. Reliable, neutral delivery.",
    minTier: "solo",
  },

  // ── Creator vibe ─────────────────────────────────────────────────────────
  {
    id: "stock-creator-01",
    name: "Layla",
    imageUrl: "https://i.pravatar.cc/600?img=47",
    thumbnailUrl: "https://i.pravatar.cc/150?img=47",
    gender: "female",
    vibe: "creator",
    description: "Native short-form creator. Hooks within 2 seconds.",
    minTier: "creator",
  },
  {
    id: "stock-creator-02",
    name: "Kai",
    imageUrl: "https://i.pravatar.cc/600?img=68",
    thumbnailUrl: "https://i.pravatar.cc/150?img=68",
    gender: "male",
    vibe: "creator",
    description: "UGC-style energy. Reads like a trending Reel.",
    minTier: "creator",
  },
  {
    id: "stock-creator-03",
    name: "Mika",
    imageUrl: "https://i.pravatar.cc/600?img=32",
    thumbnailUrl: "https://i.pravatar.cc/150?img=32",
    gender: "neutral",
    vibe: "creator",
    description: "Gen-Z cadence. Casual, irreverent, lands hot takes cleanly.",
    minTier: "creator",
  },
  {
    id: "stock-creator-04",
    name: "Violet",
    imageUrl: "https://i.pravatar.cc/600?img=24",
    thumbnailUrl: "https://i.pravatar.cc/150?img=24",
    gender: "female",
    vibe: "creator",
    description: "Aesthetic-first vlogger. Atmospheric, expressive.",
    minTier: "creator",
  },
  {
    id: "stock-creator-05",
    name: "Ronan",
    imageUrl: "https://i.pravatar.cc/600?img=57",
    thumbnailUrl: "https://i.pravatar.cc/150?img=57",
    gender: "male",
    vibe: "creator",
    description: "Booktok / insightsTok vibes. Thoughtful sincerity.",
    minTier: "creator",
  },

  // ── Expert vibe (new) — deep-domain authority ────────────────────────────
  {
    id: "stock-expert-01",
    name: "Dr. Lena",
    imageUrl: "https://i.pravatar.cc/600?img=41",
    thumbnailUrl: "https://i.pravatar.cc/150?img=41",
    gender: "female",
    vibe: "expert",
    description: "Academic poise. Research-anchored, unhurried.",
    minTier: "solo",
  },
  {
    id: "stock-expert-02",
    name: "Adrien",
    imageUrl: "https://i.pravatar.cc/600?img=52",
    thumbnailUrl: "https://i.pravatar.cc/150?img=52",
    gender: "male",
    vibe: "expert",
    description: "Consultant authority. Confident and structural.",
    minTier: "solo",
  },
  {
    id: "stock-expert-03",
    name: "Meera",
    imageUrl: "https://i.pravatar.cc/600?img=19",
    thumbnailUrl: "https://i.pravatar.cc/150?img=19",
    gender: "female",
    vibe: "expert",
    description: "Policy analyst voice. Measured, evidence-first.",
    minTier: "creator",
  },
  {
    id: "stock-expert-04",
    name: "Omar",
    imageUrl: "https://i.pravatar.cc/600?img=60",
    thumbnailUrl: "https://i.pravatar.cc/150?img=60",
    gender: "male",
    vibe: "expert",
    description: "Operator turned analyst. Speaks from lived experience.",
    minTier: "solo",
  },

  // ── Builder vibe (new) — indie devs, makers, shippers ────────────────────
  {
    id: "stock-builder-01",
    name: "Sol",
    imageUrl: "https://i.pravatar.cc/600?img=64",
    thumbnailUrl: "https://i.pravatar.cc/150?img=64",
    gender: "neutral",
    vibe: "builder",
    description: "Keyboard-first maker energy. Build-in-public cadence.",
    minTier: null,
  },
  {
    id: "stock-builder-02",
    name: "Tatiana",
    imageUrl: "https://i.pravatar.cc/600?img=36",
    thumbnailUrl: "https://i.pravatar.cc/150?img=36",
    gender: "female",
    vibe: "builder",
    description: "Weekend-warrior shipper. Show-don't-tell cadence.",
    minTier: "starter",
  },
  {
    id: "stock-builder-03",
    name: "Arvid",
    imageUrl: "https://i.pravatar.cc/600?img=67",
    thumbnailUrl: "https://i.pravatar.cc/150?img=67",
    gender: "male",
    vibe: "builder",
    description: "Open-source maintainer voice. Practical, no hype.",
    minTier: "starter",
  },
  {
    id: "stock-builder-04",
    name: "Jin",
    imageUrl: "https://i.pravatar.cc/600?img=4",
    thumbnailUrl: "https://i.pravatar.cc/150?img=4",
    gender: "neutral",
    vibe: "builder",
    description: "Hackathon-winner energy. Fast, sharp, a little nerdy.",
    minTier: null,
  },
  {
    id: "stock-builder-05",
    name: "Saira",
    imageUrl: "https://i.pravatar.cc/600?img=28",
    thumbnailUrl: "https://i.pravatar.cc/150?img=28",
    gender: "female",
    vibe: "builder",
    description: "Technical co-founder. Writes-and-ships cadence.",
    minTier: "starter",
  },
  {
    id: "stock-builder-06",
    name: "Devon",
    imageUrl: "https://i.pravatar.cc/600?img=55",
    thumbnailUrl: "https://i.pravatar.cc/150?img=55",
    gender: "male",
    vibe: "builder",
    description: "Infra-engineer voice. Dry wit, tight architectural points.",
    minTier: "solo",
  },

  // ── Seller vibe (new) — course creators, agencies, consultants ──────────
  {
    id: "stock-seller-01",
    name: "Celeste",
    imageUrl: "https://i.pravatar.cc/600?img=16",
    thumbnailUrl: "https://i.pravatar.cc/150?img=16",
    gender: "female",
    vibe: "seller",
    description: "Course-creator polish. Pitches outcomes confidently.",
    minTier: "starter",
  },
  {
    id: "stock-seller-02",
    name: "Roman",
    imageUrl: "https://i.pravatar.cc/600?img=66",
    thumbnailUrl: "https://i.pravatar.cc/150?img=66",
    gender: "male",
    vibe: "seller",
    description: "Agency owner voice. Authority without pressure.",
    minTier: "starter",
  },
  {
    id: "stock-seller-03",
    name: "Noa",
    imageUrl: "https://i.pravatar.cc/600?img=39",
    thumbnailUrl: "https://i.pravatar.cc/150?img=39",
    gender: "female",
    vibe: "seller",
    description: "Ex-sales-leader warmth. Story-first pitching.",
    minTier: "solo",
  },
  {
    id: "stock-seller-04",
    name: "Hank",
    imageUrl: "https://i.pravatar.cc/600?img=58",
    thumbnailUrl: "https://i.pravatar.cc/150?img=58",
    gender: "male",
    vibe: "seller",
    description: "B2B closer cadence. Short sentences, hard outcomes.",
    minTier: "solo",
  },
  {
    id: "stock-seller-05",
    name: "Rekha",
    imageUrl: "https://i.pravatar.cc/600?img=23",
    thumbnailUrl: "https://i.pravatar.cc/150?img=23",
    gender: "female",
    vibe: "seller",
    description: "Consultant confidence. Leans into frameworks.",
    minTier: "starter",
  },
  {
    id: "stock-seller-06",
    name: "Isa",
    imageUrl: "https://i.pravatar.cc/600?img=10",
    thumbnailUrl: "https://i.pravatar.cc/150?img=10",
    gender: "female",
    vibe: "seller",
    description: "Coaching-business cadence. Aspirational + practical.",
    minTier: "creator",
  },
  {
    id: "stock-seller-07",
    name: "Blaise",
    imageUrl: "https://i.pravatar.cc/600?img=69",
    thumbnailUrl: "https://i.pravatar.cc/150?img=69",
    gender: "male",
    vibe: "seller",
    description: "Fractional exec voice. Pattern-library pitching.",
    minTier: "solo",
  },

  // ── Additional founders/creators to round out to 50 ──────────────────────
  {
    id: "stock-founder-06",
    name: "Ines",
    imageUrl: "https://i.pravatar.cc/600?img=30",
    thumbnailUrl: "https://i.pravatar.cc/150?img=30",
    gender: "female",
    vibe: "founder",
    description: "Bootstrapped-B2B voice. Realist, revenue-first framing.",
    minTier: "starter",
  },
  {
    id: "stock-founder-07",
    name: "Oren",
    imageUrl: "https://i.pravatar.cc/600?img=53",
    thumbnailUrl: "https://i.pravatar.cc/150?img=53",
    gender: "male",
    vibe: "founder",
    description: "Ex-BigCo founder cadence. Credibility-first delivery.",
    minTier: "starter",
  },
  {
    id: "stock-host-05",
    name: "Clem",
    imageUrl: "https://i.pravatar.cc/600?img=27",
    thumbnailUrl: "https://i.pravatar.cc/150?img=27",
    gender: "neutral",
    vibe: "host",
    description: "Indie podcast vibe. Niche-deep and conversational.",
    minTier: "starter",
  },
  {
    id: "stock-creator-06",
    name: "Saskia",
    imageUrl: "https://i.pravatar.cc/600?img=45",
    thumbnailUrl: "https://i.pravatar.cc/150?img=45",
    gender: "female",
    vibe: "creator",
    description: "Career-pivoter voice. High emotional resonance.",
    minTier: "creator",
  },
  {
    id: "stock-builder-07",
    name: "Pavel",
    imageUrl: "https://i.pravatar.cc/600?img=62",
    thumbnailUrl: "https://i.pravatar.cc/150?img=62",
    gender: "male",
    vibe: "builder",
    description: "Systems-designer calm. Explains architectures crisply.",
    minTier: "solo",
  },
  {
    id: "stock-expert-05",
    name: "Aarav",
    imageUrl: "https://i.pravatar.cc/600?img=54",
    thumbnailUrl: "https://i.pravatar.cc/150?img=54",
    gender: "male",
    vibe: "expert",
    description: "Quant-background voice. Numbers-heavy but clear.",
    minTier: "creator",
  },
  {
    id: "stock-teacher-06",
    name: "Camille",
    imageUrl: "https://i.pravatar.cc/600?img=38",
    thumbnailUrl: "https://i.pravatar.cc/150?img=38",
    gender: "female",
    vibe: "teacher",
    description: "Workshop-leader energy. Keeps rooms engaged.",
    minTier: "solo",
  },
  {
    id: "stock-reporter-05",
    name: "Eitan",
    imageUrl: "https://i.pravatar.cc/600?img=3",
    thumbnailUrl: "https://i.pravatar.cc/150?img=3",
    gender: "male",
    vibe: "reporter",
    description: "Tech-reporter urgency. Great for launch videos.",
    minTier: "solo",
  },
  {
    id: "stock-seller-08",
    name: "Yuki",
    imageUrl: "https://i.pravatar.cc/600?img=42",
    thumbnailUrl: "https://i.pravatar.cc/150?img=42",
    gender: "female",
    vibe: "seller",
    description: "Growth-marketer cadence. Funnel-first framing.",
    minTier: "solo",
  },
  {
    id: "stock-host-06",
    name: "Orson",
    imageUrl: "https://i.pravatar.cc/600?img=70",
    thumbnailUrl: "https://i.pravatar.cc/150?img=70",
    gender: "male",
    vibe: "host",
    description: "Weekend-podcast voice. Meandering in a charming way.",
    minTier: "starter",
  },
];

export const AVATAR_VIBE_LABELS = {
  founder: "Founder",
  host: "Host",
  teacher: "Teacher",
  reporter: "Reporter",
  creator: "Creator",
  expert: "Expert",
  builder: "Builder",
  seller: "Seller",
} as const;
