import { notFound } from "next/navigation";
import type { Metadata } from "next";
import { getPseoPage } from "@/lib/services/db";

interface Props {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { slug } = await params;
  const page = await getPseoPage(slug).catch(() => null);
  if (!page) return { title: "Not Found" };
  return {
    title: page.title,
    description: page.metaDescription,
    openGraph: {
      title: page.title,
      description: page.metaDescription,
      images: page.ogImage ? [{ url: page.ogImage }] : [],
      type: "article",
    },
    alternates: { canonical: page.canonicalUrl },
  };
}

export default async function PseoPage({ params }: Props) {
  const { slug } = await params;
  const page = await getPseoPage(slug).catch(() => null);
  if (!page) notFound();

  return (
    <main className="mx-auto max-w-3xl px-4 py-12 sm:px-6 lg:py-16">
      {/* Structured data for Google video indexing */}
      {page.videoObjectJsonLd && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: page.videoObjectJsonLd }}
        />
      )}
      {page.faqJson && (
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: page.faqJson }}
        />
      )}

      <h1 className="font-serif text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-50 sm:text-4xl">
        {page.title}
      </h1>

      {/* Video embed — shows when a rendered video URL is stored on the page */}
      {page.ogImage && (
        <div className="mt-8 overflow-hidden rounded-xl bg-black aspect-video">
          <video
            controls
            playsInline
            poster={page.ogImage}
            className="h-full w-full object-contain"
            aria-label={page.title}
          >
            {/* videoUrl is not yet in PseoPage type; the poster/thumbnail is the fallback */}
            <source src={page.ogImage.replace(/\.(jpg|jpeg|png|webp)$/, ".mp4")} type="video/mp4" />
            Your browser does not support video playback.
          </video>
        </div>
      )}

      {/* Article content — sanitized HTML generated by Claude Sonnet */}
      <div
        className="prose prose-gray dark:prose-invert mt-10 max-w-none"
        dangerouslySetInnerHTML={{ __html: page.htmlContent }}
      />

      <footer className="mt-16 border-t border-gray-200 pt-8 dark:border-gray-800">
        <p className="text-sm text-gray-500 dark:text-gray-400">
          Published by{" "}
          <a
            href="https://buildinsocial.com"
            className="font-medium text-brand-500 hover:text-brand-400"
          >
            Build In Social
          </a>
        </p>
      </footer>
    </main>
  );
}
